<!DOCTYPE html>
<!-- GeekWisdom.org - Themeable Site / W3C Compliant - Brad Detchevery -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<!-- -->
<html lang="en">
<head><title>TITLE</title>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112001731-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-112001731-1');
</script>


<link rel="alternate" type="application/rss+xml" title="title - RSS" href="siterss" />
<!--[if lt IE 9]-->
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js">
</script>
<!--[endif]-->
<link id="MainStyle" rel="stylesheet" type="text/css" href="/themes/gw-theme.css" />

<!--  ClickJack /Javascript Helper -->
<style id="noJavascriptStyle">
    #noJavascript {display:none !important;}
</style>
<script src="./scripts/org/geekwisdom/logging/gwLogger.js"></script>
<script src="./scripts/org/geekwisdom/settings/gwSettings.js"></script>
<!-- Standard Meta data -->
<meta name="Author" CONTENT="">
<meta name="Publisher" CONTENT="">
<meta name="Content-Language" CONTENT="en-US">
<meta name="description" content="">


<!-- Open Graph metadata -->
<meta property="og:type" content="website" />
<meta property="og:site_name" content="" />
<meta property="og:image" content="" />

<!-- Twitter metadata -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="">
<meta name="twitter:title" content="">
<meta name="twitter:description" content="">
</head>
